# Generated by Django 5.0.4 on 2024-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_contact_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account_images/', verbose_name='تصویر'),
        ),
    ]
