# Generated by Django 5.0.4 on 2024-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_reply',
            field=models.TextField(default=None, verbose_name='پاسخ ادمین'),
        ),
    ]
