# Generated by Django 5.0.4 on 2024-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_ticket_admin_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='admin_reply',
            field=models.TextField(default='', verbose_name='پاسخ ادمین'),
        ),
    ]
