# Generated by Django 5.0.4 on 2024-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_alter_ticket_admin_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(verbose_name='موضوع'),
        ),
    ]
