# Generated by Django 5.0.4 on 2024-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_saved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
