# Generated by Django 5.0.4 on 2024-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_post_total_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='total_saved',
            new_name='total_saves',
        ),
    ]
