# Generated by Django 5.0.4 on 2024-05-28 15:18

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_user_facebook_id_user_insta_id_user_twitter_id'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='C:/Users/masoud/Desktop/djangoProject/masoudsocial/social/static/images/profile/Avatar - Copy.png', null=True, upload_to='account_images/', verbose_name='تصویر'),
        ),
    ]
