# Generated by Django 5.0.4 on 2024-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_alter_post_tags_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account_images/', verbose_name='تصویر'),
        ),
    ]
