# Generated by Django 5.1.4 on 2024-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_remove_comment_name_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
    ]
